# This is a basic workflow to help you get started with Actions

name: check_api

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "5-55/10 * * * *"
  repository_dispatch:
    types: check_api    
  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
            node-version: 16.x
      - name: npm install
        run: |
            npm install
      - name: "运行 check_api"
        run: |
            node index.js
      
